
build-debian:
  stage: build
  tags:
    - debian
  artifacts:
    untracked: true
  script: 
    - mkdir build && cd build
    - cmake -DBUILD_TESTS=ON -DBUILD_EXAMPLES=ON ..
    - cmake --build . --config Release

build-windows:
  stage: build
  tags:
    - windows
  artifacts:
    untracked: true
  script:
    - mkdir build
    - cd build
    - cmake -DBUILD_TESTS=ON -DBUILD_EXAMPLES=ON ..
    - cmake --build . --config Release

build-macos:
  stage: build
  tags:
    - macos
  artifacts:
    untracked: true
  script:
    - mkdir build && cd build
    - cmake -DBUILD_TESTS=ON -DBUILD_EXAMPLES=ON ..
    - cmake --build . --config Release

test-debian:
  stage: test
  tags:
    - debian
  dependencies:
    - build-debian
  script:
    - cd build
    - ctest --output-on-failure . 

test-windows:
  stage: test
  tags:
    - windows
  dependencies:
    - build-windows
  script:
    - cd build
    - ctest --output-on-failure . 

test-macos:
  stage: test
  tags:
    - macos
  dependencies:
    - build-macos
  script:
    - cd build
    - ctest --output-on-failure . 